name: run main.py

on:
  schedule:
    - cron: '*/10 * * * *' # runs at every 12AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: execute py script # run main.py
        run: curl https://speedx-kzwc.onrender.com/api/bookings/allbooking
          
